### ISSUE TITLE
error config

### ISSUE THREAD

**Issue by ryolaxe** [custom-components/grocy#15]
Hello,

I've been trying to add this custom component, but it freezes the web interface as soon as I install it.

this is my config :

```
grocy:
  url: "https://xxx.duckdns.org/a0d7b954_grocy/api/"
  api_key: "xxxxxx"
  sensor:
    - enabled: true
```

I don't have anything in the logs.

Can someone help ?

Thanks!

**Comment by RolandGoud** [comment]
same here...

**Comment by Dupz88** [comment]
Same here.
I figured my SD died as hassio would not let me back in. I flashed a new card, restored my backup. Installed grocy addon, ran it. I installed this. Restarted, all good. 

Put in the config.yaml info.
Restarted. Now my frontend loads up the overview (may be my cache) and I get "Unable to load the panel source: /api/hassio/app/entrypoint.js." on anything I click on.

**Comment by SebRut** [comment]
Very strange issue. Could you guys check if you can access the api with the url specified in the config just to make sure it's not the HASSIO port problem others described over here.

> I don't have anything in the logs.
Is there really no mention of grocy in the logs at all or just no error message?

**Comment by ludeeus** [comment]
AFAIK ingress URL's can't be used in integrations

**Comment by SebRut** [comment]
> AFAIK ingress URL's can't be used in integrations

tbh I don't have any experience with Hassio and stuff I just remembered that some people using it had connection issues before. Nevertheless I should add better logging.

**Comment by ryolaxe** [comment]
With the URL specified, I arrive to grouchy main page. Is it ok ? Or is there a special place for the api ?

Thanks

**Comment by ludeeus** [comment]
And due to ingress that is expected.
but if you try the same in an incognito window you will get the HA login screen, a python package does not know what to do there.

My suggestion is that in the configuration for that Add-on `https://xxx.duckdns.org/hassio/addon/a0d7b954_grocy`
Set a port in the network section to `13131` (example), then restart the Add-on

Then adjust your HA configuration, run a config-check, then restart HA when that passes

```
# Again example
grocy:
  url: "https://a0d7b954_grocy:13131/api/"
  verify_ssl: false
  api_key: "xxxxxx"
  sensor:
    - enabled: true
```

if `"https://a0d7b954_grocy:13131/api/"` still fail, try `"https://IP_ADDRESS_TO_YOUR_HASSIO:13131/api/"`
