### ISSUE TITLE
[Question] Pull chore data for daily notification

### ISSUE THREAD

**Issue by dinki** [custom-components/grocy#256]
Hi.  Thanks again for this great integration.  My family and I have been using it for chore tracking and what a difference it has made in our home.  

I am writing to ask if someone can tell me a way to pull data from this integration for use in a daily notification to each member of my household.  I'd like to pull all chores due today and overdue that I can then push via a notification.   I'm fine with templating this but it is beyond my skill level.  Any help would be most appreciated

**Comment by JonSp8** [comment]
Try an automation like this [one](https://www.reddit.com/r/grocy/comments/uzuwgo/comment/iapdf32/?utm_source=share&utm_medium=web2x&context=3):

I've also added my slightly modified version below:
```
alias: Notify daily chore reminder
description: ""
trigger:
  - platform: sun
    event: sunrise
    offset: 0
condition: []
action:
  - service: notify.notify
    data:
      message: >-
        Chores: {% for chore in
        state_attr('sensor.grocy_chores','chores') if
        strptime(chore.next_estimated_execution_time,
        '%Y-%m-%dT%H:%M:%S')|as_local <= today_at('23:59:59') %} {{chore.name}}
        {% else %} -None! {% endfor %}


```

This will send a daily reminder at [trigger] sunset and will use the [service] notify.notify to notify all available devices.
