### ISSUE TITLE
Support for by barcode

### ISSUE THREAD

**Issue by phil-schneider** [custom-components/grocy#324]
Hello,
Are there an Plan to Support Operations by barcode?
Like "Add Product To Stock" or "Consume Product From Stock"
I have a barcode Scanner and want to use Service to add or cobsume from Stock.
I saw the python api Supports this.
If there are no plans, is there a Chance that a PR will get accepted and merged?
I would create a fork, work on this and if everything is working create a PR back to you.

What Do you think?

**Comment by phil-schneider** [comment]
So a short update:
I have a version working with "by barcode". Need to spend some more time. But I can add a product to stock or consume a product to stock all by barcode instead id.

Why is this needed? Because this:
https://github.com/SmartHome-yourself/barcode-scanner-for-esphome
I want to change the code from this esphome, to read the ean barcode and call the service.

What is needed, besides running code, for a pull request?

**Comment by V69dxz** [comment]
That is very cool!

Right now, I use a workaround by using the rest api integration in HA

```
rest_command:
  lookup_product:
    url: "http://XXX:9192/api/stock/products/by-barcode/{{ barcode }}"
    method: GET
    headers:
      GROCY-API-KEY: !secret grocy_api
    timeout: 10
```

The {barcode} is fetched by my esp barcode scanner.
