### ISSUE TITLE
Grocy sensors no longer appear

### ISSUE THREAD

**Issue by PurelyNicole** [custom-components/grocy#36]
**Describe the bug**
I updated to 0.4.0 through HACS, and my Grocy sensors have disappeared. I am running Grocy as a Hassio install. I do not see any Grocy errors in my logs.

**Are you using HASSIO to run grocy?**
Yes

**configuration.yaml entry**
```yaml
grocy:
  url: https://MY_URL
  api_key: !secret grocy_api
  verify_ssl: true
  port: 9192
  sensor:
    - enabled: true
  binary_sensor:
    - enabled : true
```
