### ISSUE TITLE
Chore sensor does not contain user assignments

### ISSUE THREAD

**Issue by zigurana** [custom-components/grocy#44]
**Describe the bug**
The Grocy API supplies `next_execution_assigned_to_user_id`, but this is not reported by the sensor.
Therefore it cannot be used as an info source for Lovelace Cards etc.
(Grocy Custom Component v. 0.4.0)

**To Reproduce**
1. Go to 'HomeAssistant > Development tools > States'
2. Select sensor.grocy_chores entity
3. Inspect values for chores, see:
```
  - _chore_id: 1
    _last_tracked_time: '2020-04-07T00:00:00+00:00'
    _next_estimated_execution_time: '2020-04-12T00:00:00+00:00'
    _name: Planten watergeven
    _last_done_by:
      _id: 3
      _username: Jannica
      _first_name: Janneke
      _last_name: ''
      _display_name: Janneke
  - _chore_id: 2
    _last_tracked_time: '2020-04-08T00:00:00+00:00'
    _next_estimated_execution_time: '2020-04-09T00:00:00+00:00'
    _name: Afwassen
    _last_done_by:
      _id: 1
      _username: admin
      _first_name: null
      _last_name: null
      _display_name: admin
```
4. No entry for `_next_execution_assigned_to_user_id` is found.

**Expected behavior**
`next_execution_assigned_to_user_id` should also be part of the sensor data.

**Are you using HASSIO to run grocy?**
Yes

**configuration.yaml entry**
```yaml
default
```
Grocy config = default

**JSON service data (if related to using a service)**
```json
{

}
```

**Additional context**
