### ISSUE TITLE
Can't install component

### ISSUE THREAD

**Issue by excalbian** [custom-components/grocy#72]
**Describe the bug**
I have followed the instructions in `readme` for installing the custom component using HACS (I'm on a Rasberry Pi 3 with Hassio and have Grocy from the add-on store). When I try to add the integration from the UI (step 10) it spins for a while and just returns to the list of integrations.

I also tried adding the configuration (details below) to configuration.yaml, with similar results. I do get a message in the HA logs that `2020-08-15 11:15:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for grocy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.` but still don't see any states (or services) from the custom component in developer tools and Grocy says the API Key has never been used.

**To Reproduce**
1. Install Grocy from the Add-on store
2. In the 'Network' section of the add-on config, input 9192 in the host field.
3. Go to Grocy > Wrench icon > Manage API keys > Add
4. Install the Grocy integration component using HACS
5. Restart Home Assistant
6. In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Grocy"
7. After spinning for a while the panel will close and return to the list of integrations.

**Expected behavior**
Trying to use the grocy component to integrate tasks and lists within HA.

**Are you using HASSIO to run grocy?**
Yes

**configuration.yaml entry**
```yaml
grocy:
  url: "http://a0d7b954_grocy"
  api_key: "FvoGibgK2UVSo0Uudyoq6Unchitu5vhCQKmrLWk4rkze07DgCz"
  verify_ssl: false
  port: 9192
  sensor:
    - enabled: true
  binary_sensor:
    - enabled : true
```

**Additional context**
Have been facing this issue since HA 110 - just updated to 114 and still have the same experience.
