### ISSUE TITLE
Could not update data - HTTPSConnectionPool

### ISSUE THREAD

**Issue by r1kkie** [custom-components/grocy#8]
I cant get this to work :(

Advise is appriciated

My config:
```
grocy:
  url: https://xxxxx.duckdns.org:8686/api/
  api_key: pO2J6K0txxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  sensor:
    - enabled: true
```

Logs says this:
`2019-07-25 22:46:39 ERROR (MainThread) [custom_components.grocy] Could not update data - HTTPSConnectionPool(host='xxxxx.duckdns.org', port=8686): Max retries exceeded with url: /api/stock (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x72673650>: Failed to establish a new connection: [Errno 111] Connection refused'))
`
